apiVersion: v1
kind: Namespace
metadata:
  name: emqx
  labels:
    app: emqx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  labels:
    app: emqx
  namespace: emqx  
spec:
  replicas: 2
  selector:
   matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:latest
        ports:
        - name: emqx-dashboard
          containerPort: 18083
        env:
        - name: EMQX_CLUSTER__DISCOVERY
          value: k8s
        - name: EMQX_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__APISERVER
          value: https://kubernetes.default
        - name: EMQX_CLUSTER__K8S__NAMESPACE
          value: emqx
        - name: EMQX_CLUSTER__K8S__SERVICE_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
          value: ip
        - name: EMQX_CLUSTER__K8S__APP_NAME
          value: emqx
        tty: true
        volumeMounts:
          - name: logs
            mountPath: /opt/emqx/log/
      serviceAccount: emqx-sa  
      volumes:
        - name: logs
          emptyDir: {} 
---
apiVersion: v1
kind: Service
metadata:
  name: emqx
  labels:
    name: emqx
    app: emqx
  namespace: emqx
spec:
  selector:
    app: emqx
  type: NodePort
  ports:
  - name: mqtt
    nodePort: 31883
    port: 1883
    targetPort: 1883
    protocol: TCP
  - name: mqtt-http
    nodePort: 30083
    port: 18083
    targetPort: 18083
    protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: emqx
  name: emqx-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: emqx
  name: emqx-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints 
  verbs: 
  - get
  - watch
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: emqx
  name: emqx-rb
subjects:
  - kind: ServiceAccount
    name: emqx-sa
    namespace: emqx
roleRef:
  kind: Role
  name: emqx-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: emqx-dashboard
  annotations:
    kubernetes.io/ingress.class: traefik
    app: emqx
spec:
  rules:
  - host: emqx.apps.picluster
    http:
      paths:
      - backend:
          serviceName: emqx
          servicePort: 18083