---
- hosts: server
  become: yes
  become_method: sudo
  vars:
    coredns_ver: "1.9.3"
    arch: "arm"
#    arch: "amd64"
  tasks:
  - name: Ensure CoreDNS Directory
    become: yes
    file:
        path: /etc/coredns
        state: directory
        owner: root
        group: root
        mode: 0755

  - name: Copy CoreDNS Service File
    become: yes
    copy:
        src: ./coredns/{{ item }}
        dest: /etc/coredns/{{ item }}
        owner: root
        group: root
        mode: 0644
    with_items:
    - Corefile
    - db.picluster
    - db.local

  - name: Copy CoreDNS Service File
    become: yes
    copy:
        src: ./coredns/coredns.service
        dest: /etc/systemd/system/coredns.service
        owner: root
        group: root
        mode: 0644

  - name: Download CoredDNS
    get_url:
        url: https://github.com/coredns/coredns/releases/download/v{{ coredns_ver}}/coredns_{{ coredns_ver }}_linux_{{ arch }}.tgz
        dest: /tmp/coredns.tgz
        mode: 0755

  - name: Extract CoreDNS
    become: yes
    unarchive:
        src: /tmp/coredns.tgz
        dest: /usr/bin/
        remote_src: yes

  - name: Enable CoreDNS
    become: yes
    service:
        name: coredns
        enabled: yes
        state: started
  - name: Install dnsutils
    apt:
      name: dnsutils
