apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-influxdb-pvc
  namespace: kube-system
  labels:
    k8s-app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
